/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    menu: Menu;
    team: Team;
    'wine-list': WineList;
    spaces: Space;
    announcements: Announcement;
    testimonials: Testimonial;
    'dining-experiences': DiningExperience;
    tables: Table;
    schedules: Schedule;
    reservations: Reservation;
    customers: Customer;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      bookings: 'reservations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'wine-list': WineListSelect<false> | WineListSelect<true>;
    spaces: SpacesSelect<false> | SpacesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'dining-experiences': DiningExperiencesSelect<false> | DiningExperiencesSelect<true>;
    tables: TablesSelect<false> | TablesSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'fr';
  widgets: {
    'reservation-todays-reservations': ReservationTodaysReservationsWidget;
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: {
      cancelStaleReservations: TaskCancelStaleReservations;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  /**
   * Course name (e.g. Starters, Mains, Cheese, Desserts)
   */
  name: string;
  description?: string | null;
  image?: (string | null) | Media;
  dishes?:
    | {
        name: string;
        description?: string | null;
        price: number;
        dietary?: ('vegetarian' | 'vegan' | 'gluten-free' | 'dairy-free' | 'nut-free')[] | null;
        /**
         * Mark as seasonal / limited availability
         */
        seasonal?: boolean | null;
        /**
         * Chef's recommendation
         */
        chefRecommendation?: boolean | null;
        /**
         * Suggested wine pairing
         */
        winePairing?: (string | null) | WineList;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wine-list".
 */
export interface WineList {
  id: string;
  /**
   * e.g. "Château Margaux 2015"
   */
  name: string;
  type: 'red' | 'white' | 'rose' | 'champagne' | 'dessert';
  /**
   * e.g. "Bordeaux, France" or "Tuscany, Italy"
   */
  region: string;
  /**
   * Year of production
   */
  vintage?: number | null;
  /**
   * e.g. "Cabernet Sauvignon / Merlot blend"
   */
  grape?: string | null;
  tastingNotes?: string | null;
  /**
   * What dishes this wine pairs well with
   */
  pairingNotes?: string | null;
  /**
   * Price per glass (leave empty if bottle only)
   */
  priceGlass?: number | null;
  priceBottle: number;
  image?: (string | null) | Media;
  /**
   * Show on homepage wine section
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  name: string;
  role: 'head-chef' | 'sous-chef' | 'pastry-chef' | 'sommelier' | 'maitre-d' | 'bartender';
  photo?: (string | null) | Media;
  bio?: string | null;
  /**
   * e.g. "Classical French sauces" or "Natural wines"
   */
  specialty?: string | null;
  /**
   * Their most famous creation
   */
  signatureDish?: string | null;
  awards?:
    | {
        title: string;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces".
 */
export interface Space {
  id: string;
  name: string;
  description?: string | null;
  featuredImage: string | Media;
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Maximum number of seated guests
   */
  capacity: number;
  features?:
    | (
        | 'natural-light'
        | 'garden-view'
        | 'fireplace'
        | 'sound-system'
        | 'projector'
        | 'private-entrance'
        | 'bar-access'
        | 'outdoor'
      )[]
    | null;
  /**
   * Available for private event bookings
   */
  privateEventAvailable?: boolean | null;
  /**
   * Minimum spend for private events (€)
   */
  minimumSpend?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  title: string;
  description?: string | null;
  type: 'seasonal-menu' | 'special-event' | 'holiday-menu' | 'chef-collab' | 'live-entertainment' | 'wine-tasting';
  image?: (string | null) | Media;
  startDate: string;
  /**
   * Leave empty for single-day events
   */
  endDate?: string | null;
  /**
   * Button text (e.g. "Reserve Now", "Learn More")
   */
  ctaText?: string | null;
  ctaLink?: string | null;
  active?: boolean | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  author: string;
  rating: number;
  diningExperience?: (string | null) | DiningExperience;
  /**
   * Which dining space was the guest seated in
   */
  space?: (string | null) | Space;
  visitDate?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dining-experiences".
 */
export interface DiningExperience {
  id: string;
  name: string;
  image?: (string | null) | Media;
  description?: string | null;
  duration: number;
  durationType: 'fixed' | 'flexible' | 'full-day';
  price?: number | null;
  bufferTimeBefore?: number | null;
  bufferTimeAfter?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables".
 */
export interface Table {
  id: string;
  name: string;
  image?: (string | null) | Media;
  description?: string | null;
  services: (string | DiningExperience)[];
  active?: boolean | null;
  quantity: number;
  capacityMode?: ('per-reservation' | 'per-guest') | null;
  timezone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: string;
  name: string;
  resource: string | Table;
  scheduleType?: ('recurring' | 'manual') | null;
  recurringSlots?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  manualSlots?:
    | {
        date: string;
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  exceptions?:
    | {
        date: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: string;
  service: string | DiningExperience;
  resource: string | Table;
  customer: string | Customer;
  startTime: string;
  endTime?: string | null;
  status?: ('pending' | 'confirmed' | 'completed' | 'cancelled' | 'no-show') | null;
  cancellationReason?: string | null;
  guestCount?: number | null;
  notes?: string | null;
  /**
   * Resources included in this booking. Leave empty for single-resource bookings.
   */
  items?:
    | {
        resource: string | Table;
        service?: (string | null) | DiningExperience;
        startTime?: string | null;
        endTime?: string | null;
        guestCount?: number | null;
        id?: string | null;
      }[]
    | null;
  idempotencyKey?: string | null;
  /**
   * Number of guests in the party
   */
  partySize?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  firstName: string;
  lastName: string;
  phone?: string | null;
  notes?: string | null;
  bookings?: {
    docs?: (string | Reservation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'cancelStaleReservations';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'cancelStaleReservations') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'wine-list';
        value: string | WineList;
      } | null)
    | ({
        relationTo: 'spaces';
        value: string | Space;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'dining-experiences';
        value: string | DiningExperience;
      } | null)
    | ({
        relationTo: 'tables';
        value: string | Table;
      } | null)
    | ({
        relationTo: 'schedules';
        value: string | Schedule;
      } | null)
    | ({
        relationTo: 'reservations';
        value: string | Reservation;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  dishes?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        dietary?: T;
        seasonal?: T;
        chefRecommendation?: T;
        winePairing?: T;
        id?: T;
      };
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  specialty?: T;
  signatureDish?: T;
  awards?:
    | T
    | {
        title?: T;
        year?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wine-list_select".
 */
export interface WineListSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  region?: T;
  vintage?: T;
  grape?: T;
  tastingNotes?: T;
  pairingNotes?: T;
  priceGlass?: T;
  priceBottle?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces_select".
 */
export interface SpacesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  capacity?: T;
  features?: T;
  privateEventAvailable?: T;
  minimumSpend?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  image?: T;
  startDate?: T;
  endDate?: T;
  ctaText?: T;
  ctaLink?: T;
  active?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  rating?: T;
  diningExperience?: T;
  space?: T;
  visitDate?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dining-experiences_select".
 */
export interface DiningExperiencesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  description?: T;
  duration?: T;
  durationType?: T;
  price?: T;
  bufferTimeBefore?: T;
  bufferTimeAfter?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables_select".
 */
export interface TablesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  description?: T;
  services?: T;
  active?: T;
  quantity?: T;
  capacityMode?: T;
  timezone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  name?: T;
  resource?: T;
  scheduleType?: T;
  recurringSlots?:
    | T
    | {
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  manualSlots?:
    | T
    | {
        date?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  exceptions?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  service?: T;
  resource?: T;
  customer?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  cancellationReason?: T;
  guestCount?: T;
  notes?: T;
  items?:
    | T
    | {
        resource?: T;
        service?: T;
        startTime?: T;
        endTime?: T;
        guestCount?: T;
        id?: T;
      };
  idempotencyKey?: T;
  partySize?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  notes?: T;
  bookings?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroBackgroundImage?: (string | null) | Media;
  heroCtaText?: string | null;
  heroCtaLink?: string | null;
  storyHeading?: string | null;
  storyBody?: string | null;
  storyImage?: (string | null) | Media;
  /**
   * e.g. "Est. 1987"
   */
  storyEstablished?: string | null;
  menuHeading?: string | null;
  menuSubtitle?: string | null;
  menuCtaText?: string | null;
  menuCtaLink?: string | null;
  teamHeading?: string | null;
  teamSubtitle?: string | null;
  spacesHeading?: string | null;
  spacesSubtitle?: string | null;
  wineHeading?: string | null;
  wineSubtitle?: string | null;
  wineImage?: (string | null) | Media;
  experiencesHeading?: string | null;
  experiencesSubtitle?: string | null;
  testimonialsHeading?: string | null;
  testimonialsSubtitle?: string | null;
  announcementsHeading?: string | null;
  announcementsSubtitle?: string | null;
  ctaHeading?: string | null;
  ctaBody?: string | null;
  ctaButtonText?: string | null;
  ctaButtonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  restaurantName: string;
  logo?: (string | null) | Media;
  /**
   * e.g. "Contemporary French"
   */
  cuisineType?: string | null;
  michelinStars?: ('0' | '1' | '2' | '3') | null;
  /**
   * Short motto or slogan
   */
  tagline?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'tripadvisor' | 'twitter' | 'google-maps';
        url: string;
        id?: string | null;
      }[]
    | null;
  serviceHours?:
    | {
        service: 'lunch' | 'dinner' | 'brunch' | 'bar';
        days: string;
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  dressCode?: ('casual' | 'smart-casual' | 'business-casual' | 'formal') | null;
  parkingInfo?: string | null;
  accessibilityInfo?: string | null;
  reservationPolicy?: string | null;
  cancellationPolicy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroBackgroundImage?: T;
  heroCtaText?: T;
  heroCtaLink?: T;
  storyHeading?: T;
  storyBody?: T;
  storyImage?: T;
  storyEstablished?: T;
  menuHeading?: T;
  menuSubtitle?: T;
  menuCtaText?: T;
  menuCtaLink?: T;
  teamHeading?: T;
  teamSubtitle?: T;
  spacesHeading?: T;
  spacesSubtitle?: T;
  wineHeading?: T;
  wineSubtitle?: T;
  wineImage?: T;
  experiencesHeading?: T;
  experiencesSubtitle?: T;
  testimonialsHeading?: T;
  testimonialsSubtitle?: T;
  announcementsHeading?: T;
  announcementsSubtitle?: T;
  ctaHeading?: T;
  ctaBody?: T;
  ctaButtonText?: T;
  ctaButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  restaurantName?: T;
  logo?: T;
  cuisineType?: T;
  michelinStars?: T;
  tagline?: T;
  address?: T;
  phone?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  serviceHours?:
    | T
    | {
        service?: T;
        days?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  dressCode?: T;
  parkingInfo?: T;
  accessibilityInfo?: T;
  reservationPolicy?: T;
  cancellationPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation-todays-reservations_widget".
 */
export interface ReservationTodaysReservationsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCancelStaleReservations".
 */
export interface TaskCancelStaleReservations {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}