/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    demos: Demo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    demos: DemosSelect<false> | DemosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-page': HomePage;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'fr';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos".
 */
export interface Demo {
  id: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  emoji: string;
  /**
   * Show as live (not "Coming Soon")
   */
  active?: boolean | null;
  displayOrder?: number | null;
  /**
   * Full URL to the live demo
   */
  liveUrl?: string | null;
  name: string;
  tagline: string;
  description: string;
  /**
   * Header image for the demo card (landscape, ~640×320)
   */
  cardImage?: (string | null) | Media;
  /**
   * Short feature pills shown on the card (4 recommended)
   */
  cardFeatures?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Industry identifier, e.g. "salon", "hotel"
   */
  workflowIndustry?: string | null;
  /**
   * Heading above the features grid, e.g. "Built for salon workflows"
   */
  featuresHeading?: string | null;
  /**
   * Heading for the plugin config section, e.g. "Plugin config for Lumière Salon"
   */
  pluginConfigHeading?: string | null;
  /**
   * CTA strip heading, e.g. "Ready to explore Lumière Salon?"
   */
  detailCtaTitle?: string | null;
  /**
   * CTA strip subtitle
   */
  detailCtaSubtitle?: string | null;
  detailDescription?: string | null;
  detailFeatures?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Plugin config snippet shown on the detail page
   */
  pluginSnippet?: string | null;
  screenshots?:
    | {
        image?: (string | null) | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'demos';
        value: string | Demo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos_select".
 */
export interface DemosSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  emoji?: T;
  active?: T;
  displayOrder?: T;
  liveUrl?: T;
  name?: T;
  tagline?: T;
  description?: T;
  cardImage?: T;
  cardFeatures?:
    | T
    | {
        text?: T;
        id?: T;
      };
  workflowIndustry?: T;
  featuresHeading?: T;
  pluginConfigHeading?: T;
  detailCtaTitle?: T;
  detailCtaSubtitle?: T;
  detailDescription?: T;
  detailFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  pluginSnippet?: T;
  screenshots?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  defaultMeta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Labels and chrome for /demos/[type] pages
   */
  demoDetailUi?: {
    backToDemos?: string | null;
    visitLiveDemo?: string | null;
    demoComingSoon?: string | null;
    requestPrivateDemo?: string | null;
    featuresLabel?: string | null;
    screenshotsHeading?: string | null;
    screenshotsComingSoon?: string | null;
    screenshotsLivePromptBefore?: string | null;
    screenshotsLiveDemoLabel?: string | null;
    screenshotsLivePromptAfter?: string | null;
    configurationLabel?: string | null;
    payloadConfigFile?: string | null;
    docsNoteBefore?: string | null;
    docsLinkLabel?: string | null;
    docsNoteAfter?: string | null;
  };
  externalUrls?: {
    github?: string | null;
    docs?: string | null;
    gshell?: string | null;
    payloadcms?: string | null;
    nextjs?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  docsLabel?: string | null;
  demosLabel?: string | null;
  githubLabel?: string | null;
  requestDemoLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroSection?: {
    heroBadge?: string | null;
    heroHeadline1?: string | null;
    heroHeadline2?: string | null;
    heroSubheading?: string | null;
    heroCtaDemos?: string | null;
    heroCtaDocs?: string | null;
    /**
     * Pill tags below the CTA buttons
     */
    heroIndustryTags?:
      | {
          emoji: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  useCasesSection?: {
    useCasesLabel?: string | null;
    useCasesFootnote?: string | null;
    useCasesItems?:
      | {
          emoji: string;
          label: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  featuresSection?: {
    featuresLabel?: string | null;
    featuresHeadline1?: string | null;
    featuresHeadline2?: string | null;
    featuresSubheading?: string | null;
    featuresItems?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  demosSection?: {
    demosLabel?: string | null;
    demosHeadline?: string | null;
    demosSubheading?: string | null;
    demosComingSoon?: string | null;
    demosExploreLabel?: string | null;
    demos?: (string | Demo)[] | null;
  };
  adminUiSection?: {
    adminUiLabel?: string | null;
    adminUiHeadline?: string | null;
    adminUiSubtitle?: string | null;
    adminUiBrowserUrl?: string | null;
    /**
     * Captions shown for each screenshot slide
     */
    adminUiSlides?:
      | {
          caption: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  privateDemoSection?: {
    privateDemoLabel?: string | null;
    privateDemoHeadline?: string | null;
    privateDemoSubtitle?: string | null;
    privateDemoCta?: string | null;
    privateDemoAudience?: string | null;
    privateDemoPerks?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    privateDemoImage?: (string | null) | Media;
  };
  developerSection?: {
    devLabel?: string | null;
    devHeadline?: string | null;
    devSubtitle?: string | null;
    devCta?: string | null;
    devNote?: string | null;
    devSteps?:
      | {
          title: string;
          code?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  howItWorksSection?: {
    howLabel?: string | null;
    howHeadline?: string | null;
    howSteps?:
      | {
          title: string;
          description: string;
          code?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ctaBannerSection?: {
    ctaLabel?: string | null;
    ctaHeadline?: string | null;
    ctaSubtitle?: string | null;
    ctaButtonDocs?: string | null;
    ctaButtonGithub?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  description?: string | null;
  copyright?: string | null;
  madeByLabel?: string | null;
  builtWithLabel?: string | null;
  andLabel?: string | null;
  productSection?: {
    heading?: string | null;
    documentation?: string | null;
    liveDemo?: string | null;
    features?: string | null;
  };
  demosSection?: {
    heading?: string | null;
    salon?: string | null;
    hotel?: string | null;
    restaurant?: string | null;
    events?: string | null;
  };
  linksSection?: {
    heading?: string | null;
    github?: string | null;
    payloadCms?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  demoDetailUi?:
    | T
    | {
        backToDemos?: T;
        visitLiveDemo?: T;
        demoComingSoon?: T;
        requestPrivateDemo?: T;
        featuresLabel?: T;
        screenshotsHeading?: T;
        screenshotsComingSoon?: T;
        screenshotsLivePromptBefore?: T;
        screenshotsLiveDemoLabel?: T;
        screenshotsLivePromptAfter?: T;
        configurationLabel?: T;
        payloadConfigFile?: T;
        docsNoteBefore?: T;
        docsLinkLabel?: T;
        docsNoteAfter?: T;
      };
  externalUrls?:
    | T
    | {
        github?: T;
        docs?: T;
        gshell?: T;
        payloadcms?: T;
        nextjs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  docsLabel?: T;
  demosLabel?: T;
  githubLabel?: T;
  requestDemoLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        heroBadge?: T;
        heroHeadline1?: T;
        heroHeadline2?: T;
        heroSubheading?: T;
        heroCtaDemos?: T;
        heroCtaDocs?: T;
        heroIndustryTags?:
          | T
          | {
              emoji?: T;
              label?: T;
              id?: T;
            };
      };
  useCasesSection?:
    | T
    | {
        useCasesLabel?: T;
        useCasesFootnote?: T;
        useCasesItems?:
          | T
          | {
              emoji?: T;
              label?: T;
              description?: T;
              id?: T;
            };
      };
  featuresSection?:
    | T
    | {
        featuresLabel?: T;
        featuresHeadline1?: T;
        featuresHeadline2?: T;
        featuresSubheading?: T;
        featuresItems?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  demosSection?:
    | T
    | {
        demosLabel?: T;
        demosHeadline?: T;
        demosSubheading?: T;
        demosComingSoon?: T;
        demosExploreLabel?: T;
        demos?: T;
      };
  adminUiSection?:
    | T
    | {
        adminUiLabel?: T;
        adminUiHeadline?: T;
        adminUiSubtitle?: T;
        adminUiBrowserUrl?: T;
        adminUiSlides?:
          | T
          | {
              caption?: T;
              image?: T;
              id?: T;
            };
      };
  privateDemoSection?:
    | T
    | {
        privateDemoLabel?: T;
        privateDemoHeadline?: T;
        privateDemoSubtitle?: T;
        privateDemoCta?: T;
        privateDemoAudience?: T;
        privateDemoPerks?:
          | T
          | {
              text?: T;
              id?: T;
            };
        privateDemoImage?: T;
      };
  developerSection?:
    | T
    | {
        devLabel?: T;
        devHeadline?: T;
        devSubtitle?: T;
        devCta?: T;
        devNote?: T;
        devSteps?:
          | T
          | {
              title?: T;
              code?: T;
              id?: T;
            };
      };
  howItWorksSection?:
    | T
    | {
        howLabel?: T;
        howHeadline?: T;
        howSteps?:
          | T
          | {
              title?: T;
              description?: T;
              code?: T;
              id?: T;
            };
      };
  ctaBannerSection?:
    | T
    | {
        ctaLabel?: T;
        ctaHeadline?: T;
        ctaSubtitle?: T;
        ctaButtonDocs?: T;
        ctaButtonGithub?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  copyright?: T;
  madeByLabel?: T;
  builtWithLabel?: T;
  andLabel?: T;
  productSection?:
    | T
    | {
        heading?: T;
        documentation?: T;
        liveDemo?: T;
        features?: T;
      };
  demosSection?:
    | T
    | {
        heading?: T;
        salon?: T;
        hotel?: T;
        restaurant?: T;
        events?: T;
      };
  linksSection?:
    | T
    | {
        heading?: T;
        github?: T;
        payloadCms?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}