/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    demos: Demo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    demos: DemosSelect<false> | DemosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-page': HomePage;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos".
 */
export interface Demo {
  id: string;
  name: string;
  slug: 'salon' | 'hotel' | 'restaurant' | 'events';
  emoji: string;
  /**
   * Show as live (not "Coming Soon")
   */
  active?: boolean | null;
  displayOrder?: number | null;
  /**
   * Full URL to the live demo (leave blank if not yet deployed)
   */
  liveUrl?: string | null;
  tagline: string;
  description: string;
  /**
   * Header image for the demo card (landscape, ~640×320)
   */
  cardImage?: (string | null) | Media;
  /**
   * Short feature pills shown on the card (4 recommended)
   */
  cardFeatures?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used in "Built for {industry} workflows" heading, e.g. "salon"
   */
  workflowIndustry?: string | null;
  detailDescription?: string | null;
  detailFeatures?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Plugin config snippet shown on the detail page
   */
  pluginSnippet?: string | null;
  screenshots?:
    | {
        image?: (string | null) | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'demos';
        value: string | Demo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos_select".
 */
export interface DemosSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  emoji?: T;
  active?: T;
  displayOrder?: T;
  liveUrl?: T;
  tagline?: T;
  description?: T;
  cardImage?: T;
  cardFeatures?:
    | T
    | {
        text?: T;
        id?: T;
      };
  workflowIndustry?: T;
  detailDescription?: T;
  detailFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  pluginSnippet?: T;
  screenshots?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  defaultMeta?: {
    title?: string | null;
    description?: string | null;
  };
  externalUrls?: {
    github?: string | null;
    docs?: string | null;
    gshell?: string | null;
    payloadcms?: string | null;
    nextjs?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  docsLabel?: string | null;
  demosLabel?: string | null;
  githubLabel?: string | null;
  requestDemoLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroBadge?: string | null;
  heroHeadline1?: string | null;
  heroHeadline2?: string | null;
  heroSubheading?: string | null;
  heroCtaDemos?: string | null;
  heroCtaDocs?: string | null;
  /**
   * Pill tags below the CTA buttons, e.g. "✂️ Salon & Spa"
   */
  heroIndustryTags?:
    | {
        emoji: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  useCasesLabel?: string | null;
  useCasesFootnote?: string | null;
  useCasesItems?:
    | {
        emoji: string;
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  featuresLabel?: string | null;
  featuresHeadline1?: string | null;
  featuresHeadline2?: string | null;
  featuresSubheading?: string | null;
  featuresItems?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  adminUiLabel?: string | null;
  adminUiHeadline?: string | null;
  adminUiSubtitle?: string | null;
  adminUiBrowserUrl?: string | null;
  /**
   * Captions shown for each screenshot slide
   */
  adminUiSlides?:
    | {
        caption: string;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  privateDemoLabel?: string | null;
  privateDemoHeadline?: string | null;
  privateDemoSubtitle?: string | null;
  privatedemoCta?: string | null;
  privateDemoAudience?: string | null;
  privateDemoPerks?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  devLabel?: string | null;
  devHeadline?: string | null;
  devSubtitle?: string | null;
  devCta?: string | null;
  devNote?: string | null;
  devSteps?:
    | {
        title: string;
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  howLabel?: string | null;
  howHeadline?: string | null;
  howSteps?:
    | {
        title: string;
        description: string;
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHeadline?: string | null;
  ctaSubtitle?: string | null;
  ctaButtonDocs?: string | null;
  ctaButtonGithub?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  description?: string | null;
  copyright?: string | null;
  madeByLabel?: string | null;
  builtWithLabel?: string | null;
  andLabel?: string | null;
  productSection?: {
    heading?: string | null;
    documentation?: string | null;
    liveDemo?: string | null;
    features?: string | null;
  };
  demosSection?: {
    heading?: string | null;
    salon?: string | null;
    hotel?: string | null;
    restaurant?: string | null;
    events?: string | null;
  };
  linksSection?: {
    heading?: string | null;
    github?: string | null;
    payloadCms?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  externalUrls?:
    | T
    | {
        github?: T;
        docs?: T;
        gshell?: T;
        payloadcms?: T;
        nextjs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  docsLabel?: T;
  demosLabel?: T;
  githubLabel?: T;
  requestDemoLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroHeadline1?: T;
  heroHeadline2?: T;
  heroSubheading?: T;
  heroCtaDemos?: T;
  heroCtaDocs?: T;
  heroIndustryTags?:
    | T
    | {
        emoji?: T;
        label?: T;
        id?: T;
      };
  useCasesLabel?: T;
  useCasesFootnote?: T;
  useCasesItems?:
    | T
    | {
        emoji?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  featuresLabel?: T;
  featuresHeadline1?: T;
  featuresHeadline2?: T;
  featuresSubheading?: T;
  featuresItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  adminUiLabel?: T;
  adminUiHeadline?: T;
  adminUiSubtitle?: T;
  adminUiBrowserUrl?: T;
  adminUiSlides?:
    | T
    | {
        caption?: T;
        image?: T;
        id?: T;
      };
  privateDemoLabel?: T;
  privateDemoHeadline?: T;
  privateDemoSubtitle?: T;
  privatedemoCta?: T;
  privateDemoAudience?: T;
  privateDemoPerks?:
    | T
    | {
        text?: T;
        id?: T;
      };
  devLabel?: T;
  devHeadline?: T;
  devSubtitle?: T;
  devCta?: T;
  devNote?: T;
  devSteps?:
    | T
    | {
        title?: T;
        code?: T;
        id?: T;
      };
  howLabel?: T;
  howHeadline?: T;
  howSteps?:
    | T
    | {
        title?: T;
        description?: T;
        code?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHeadline?: T;
  ctaSubtitle?: T;
  ctaButtonDocs?: T;
  ctaButtonGithub?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  copyright?: T;
  madeByLabel?: T;
  builtWithLabel?: T;
  andLabel?: T;
  productSection?:
    | T
    | {
        heading?: T;
        documentation?: T;
        liveDemo?: T;
        features?: T;
      };
  demosSection?:
    | T
    | {
        heading?: T;
        salon?: T;
        hotel?: T;
        restaurant?: T;
        events?: T;
      };
  linksSection?:
    | T
    | {
        heading?: T;
        github?: T;
        payloadCms?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}